config/routes.rb
Rails.application.routes.draw do

  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'

  delete 'sign_out' => 'sessions#destroy'
  root to: 'main#index'

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
#constants
  if Rails.env.production?
    MIN_PASSWORD_LENGTH = 6
  else
    MIN_PASSWORD_LENGTH = 8
  end
#associations

#scopes

#acts
  acts_as_authentic do |c|
    c.merge_validates_uniqueness_of_email_field_options :case_sensitive => false
    c.merge_validates_length_of_password_field_options :minimum => MIN_PASSWORD_LENGTH
    c.validate_login_field = false
    c.session_ids = [:public]
    c.logged_in_timeout = 2.minutes
    c.ignore_blank_passwords = false

    c.crypto_provider = Authlogic::CryptoProviders::SCrypt
  end

#callbacks
  before_validation :generate_password, on: :create

#class methods

  def self.find_by_lowercase_email_or_login(login)
    self.where(arel_table[:login].lower.eq(login.downcase).or(arel_table[:email].lower.eq(login.downcase))).first
    # User.last
  end

  def self.find_by_lowercase_email_or_login!(login)
    self.where(arel_table[:login].lower.eq(login.downcase).or(arel_table[:email].lower.eq(login.downcase))).first
    # User.last
  end

#public methods
  def set_password(password, password_confirmation)
    self.password = password
    self.password_confirmation = password_confirmation
  end

#protected methods
protected
  def reset_password_token!
    self.password_token = SecureRandom.hex(10)
    save(validate: false)
  end

  def generate_password
    return if password.present?

    password = SecureRandom.hex(10)
    set_password(password, password)

    password
  end
#private methods

end

app/models/user/session.rb
class User::Session < Authlogic::Session::Base

  authenticate_with User

  # consecutive_failed_logins_limit 3
  # failed_login_ban_for 15.minutes
  # last_request_at_threshold 1.minute

  find_by_login_method :find_by_lowercase_email_or_login
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :resource_session

  include AuthlogicMethods
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def create_session(user, id = :public)
    var = (id.nil? ? '@current_session' : "@current_#{id}_session")
    instance_variable_set(var, User::Session.new(user))
    ses = instance_variable_get(var)
    ses.remember_me = true
    ses.id = :public
    ses.save
  end

protected
  def resource_session
    @current_public_session ||= User::Session.new params[:session]
  end
end

app/controllers/concerns/authlogic_methods.rb
module AuthlogicMethods
  extend ActiveSupport::Concern

  included do
    helper_method :current_user, :current_session
  end

protected

  def current_session(id = :public)
    if User.session_ids.include?(id)
      var = (id.nil? ? '@current_session' : "@current_#{id}_session")
      return instance_variable_get(var) if instance_variable_defined?(var)
      return instance_variable_set(var, User::Session.find(id))
    else
      return nil
    end
  end

  def current_user(id = :public)
    if User.session_ids.include?(id)
      var = (id.nil? ? '@current_user' : "@current_#{id}_user")
      return instance_variable_get(var) if instance_variable_defined?(var)

      instance_variable_set(var, (current_session(id) && current_session(id).record).try(:decorate))
    else
      return nil
    end
  end

  def reset_current_session(id = :public)
    var = (id.nil? ? '@current_session' : "@current_#{id}_session")
    instance_variable_defined?(var) ? remove_instance_variable(var) : true
  end

  def reset_current_user(id = :public)
    var = (id.nil? ? '@current_user' : "@current_#{id}_user")
    instance_variable_defined?(var) ? remove_instance_variable(var) : true
  end

  def reset_authlogic(id = :public)
    reset_current_session(id)
    reset_current_user(id)
  end

  def require_user
    unless current_user.present?
      respond_to do |format|
        format.html do
          redirect_to(auth_sign_in_url) and return false
        end
        format.json do
          render(json: { message: 'Forbidden', code: 403 }.to_json, status: 403) and return false
        end
      end
    end

    true
  end

  def require_no_user
    # redirect_to(root_url) and return false unless current_user.guest?
    redirect_to(root_url) and return false if current_user.present?

    true
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_filter :require_user, except: [:destroy]
  before_filter :require_no_user, only: [:new, :create]

  helper_method :resource_session

  # def new
  #   render 'auth/sessions/new.xhr', :layout => false if request.xhr?
  # end

  def create
    if create_session(params[:session])
      self.reset_authlogic

      flash[:notice] = "Welcome back #{current_user.display_name}"

      url = if session[:return_to].present?
        session[:return_to]
      else
        root_url
      end

      respond_to do |format|
        format.html { redirect_to url }
        format.js {
          render partial: 'shared/js/redirect', locals: { url: url }
        }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_url }
        format.js {
          render partial: 'shared/js/content', locals: {
            replace: '@authForm',
            with: 'auth/sessions/shared/form',
            locals: {
              :session => resource_session,
              :remote => true
            }
          }
        }
      end
    end
  end

  def destroy
    User::Session.find(:public).destroy
    session[:return_to] = nil

    redirect_to root_url
  end

protected

  def resource_session
    @current_public_session ||= User::Session.new params[:session]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

protected
  def resource_form

  end

  def method_name

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html

html
  head
    = csrf_meta_tags
    = content_for :head
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"

  body
    = render partial: "shared/navbar"

app/views/shared/_navbar.html.slim
.container
  .row
    .col-md-4
      h2
        = t('.main_title')

    - if current_user.blank?
      .col-md-6
        = simple_form_for :session, url: sign_in_url, method: :post,  html: {class: "form-inline m-t-20", role: 'form'} do |login_form|
          .form-group.col-md-5
            = login_form.input :login, label: false, placeholder: "Login", input_html: { class: 'form-control input-lg' }
          .form-group.col-md-5
            = login_form.input :password, label: false, placeholder: "Password", input_html: { class: 'form-control input-lg' }
          .form-group.col-md-2
            = login_form.submit t('.login'), class: 'btn btn-default btn-xs'
            = link_to t('.register'), '#', class: 'btn btn-default btn-xs'
    - else
      .col-md-4.col-md-offset-1.m-t-20
        h4
          => t(".hello")
          => current_user.display_name
          => "!"
      .col-md-1.m-t-20
        => link_to t('.logout'), sign_out_url, method: :delete, class: 'btn btn-default'
          / = link_to edit_my_user_url(current_user, subdomain: :my), class: "navbar__header__auth #{'navbar__header__auth-notification' unless current_user.login_delete_notified}"
          /   = current_user.decorate.avatar_image(class: 'img-responsive navbar__header__avatar')
          /   = current_user.decorate.display_name
    .col-md-2.m-t-20
      => link_to 'EN', "#", class: 'btn btn-default'
      => link_to 'RU', "#", class: 'btn btn-default'
      => link_to 'JP', "#", class: 'btn btn-default'

  .row
    ul.navbar__navs{style='margin-top: 20px'}
      li class="#{'active'}"
        = link_to t('.about'), '#', :data => { :toggle => "dropdown" }, class: 'navbar__navs__dropdown'
        ul@backgroundHover class='navbar__navs-dropdown-menu'
          li
            = link_to t('.rules'), "#"
          li
            = link_to t('.history'),"#"
      li class="#{'active'}"
        = link_to t('.news'), '#', :data => { :toggle => "dropdown" }
      li class="#{'active'}"
        = link_to t('.tournaments'), '#', :data => { :toggle => "dropdown" }
      li class="#{'active'}"
        = link_to t('.rating'), '#', :data => { :toggle => "dropdown" }
      li class="#{'active'}"
        = link_to t('.clubs'), '#', :data => { :toggle => "dropdown" }